/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ija.ija2015.windows;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author xkeryj00
 * @author xondre08
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(screenSize.width/2-150, screenSize.height/2-75, 300, 150);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLoadGame = new javax.swing.JButton();
        jButtonNewGame = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Othello - Menu");
        setPreferredSize(new java.awt.Dimension(350, 150));
        setResizable(false);

        jButtonLoadGame.setText("Načítať hru");
        jButtonLoadGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoadGameMouseClicked(evt);
            }
        });
        jButtonLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadGameActionPerformed(evt);
            }
        });

        jButtonNewGame.setText("Nová hra");
        jButtonNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewGameMouseClicked(evt);
            }
        });
        jButtonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Akcia NewGame - po stlačení tlačidla New Game. 
     */
    private void jButtonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGameActionPerformed
        
    }//GEN-LAST:event_jButtonNewGameActionPerformed
    private MainWindowNewGame panelNewGame = new MainWindowNewGame();
    private MainWindowLoadGame panelLoadGame = new MainWindowLoadGame("");
    int t=0;
    private void jButtonNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewGameMouseClicked
       if(t!=1){
            this.setSize(this.getSize().width, 425);
            panelNewGame = new MainWindowNewGame();
            panelNewGame.setBounds(0, 150, 350, 250);

            this.repaint();
            this.remove(panelLoadGame);

            this.add(panelNewGame);
            this.setVisible(true);
            t=1;
       }
    }//GEN-LAST:event_jButtonNewGameMouseClicked

    @SuppressWarnings("empty-statement")
    /**
     * Akcia Load Game - po stlačení tlačidla Load Game.
     */
    private void jButtonLoadGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadGameMouseClicked
        if(t!=2){
            String content;
            try {
                File inputFile = new File("lib/SavedGames.data");
                if(!inputFile.canRead()){
                    JOptionPane.showMessageDialog(null, "Nepodarilo sa načítať súbor s uloženými hrami.");
                    return;
                }
                if (inputFile.length()==0) {
                    JOptionPane.showMessageDialog(null, "Niesú žiadne uložené hry.");
                    return;
                }

                content = new Scanner(inputFile).useDelimiter("\\Z").next();
                if(",".equals(content))
                {
                    JOptionPane.showMessageDialog(null, "Niesú žiadne uložené hry.");
                    return;
                }
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Nepodarilo sa načítať rozohraté hry.");
                return;
            }
            panelLoadGame = new MainWindowLoadGame("");
            this.setSize(this.getSize().width, 375);
            panelLoadGame = new MainWindowLoadGame(content);
            panelLoadGame.setBounds(0, 150, 350, 200);
            this.repaint();
            this.remove(panelNewGame);
            this.add(panelLoadGame);
            this.setVisible(true);
            t=2;
        }
        
    }//GEN-LAST:event_jButtonLoadGameMouseClicked
    /**
     * Akcia Load Game vykonaná.
     */
    private void jButtonLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadGameActionPerformed

    }//GEN-LAST:event_jButtonLoadGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
		
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoadGame;
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
